---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
    checks:
        Naming/ShortVariable:
            enabled: false
        # Temporary
        Design/CouplingBetweenObjects:
            enabled: false
        Design/TooManyPublicMethods:
            enabled: false
  phpcodesniffer:
    enabled: true
ratings:
  paths:
  - "php/src/**.php"
exclude_paths:
- "**/vendor/**/*"
